version: '3.1'

services:

  elasticsearch:
   image: docker.elastic.co/elasticsearch/elasticsearch:7.1.1
   container_name: elasticsearch
   ports:
    - "9200:9200"
    - "9300:9300"
   networks:
    - docker-network
   environment:
    - discovery.type=single-node

  kibana:
   image: docker.elastic.co/kibana/kibana:7.1.1
   container_name: kibana
   ports:
    - "5601:5601"
   depends_on:
    - elasticsearch
   networks:
    - docker-network
  
networks:
  docker-network:
    driver: bridge
